// <auto-generated />
using LienXoChongUS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LienXoChongUS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231209062129_NewBook")]
    partial class NewBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LienXoChongUS.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Mark Mark",
                            Description = "Funny/Fail moments",
                            ISBN = "FAF084279",
                            ListPrice = 99.0,
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "Funny and Fail"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Nekopum",
                            Description = "Cat with Sadness",
                            ISBN = "CAT785248",
                            ListPrice = 50.0,
                            Price = 40.0,
                            Price100 = 45.0,
                            Price50 = 47.0,
                            Title = "Sadly Kitten"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Kamikaze Motani",
                            Description = "The next gen of Minato",
                            ISBN = "BRT8523215",
                            ListPrice = 150.0,
                            Price = 140.0,
                            Price100 = 110.0,
                            Price50 = 130.0,
                            Title = "Ba ru to"
                        },
                        new
                        {
                            Id = 4,
                            Author = "NekoBruh",
                            Description = "This is just a meme",
                            ISBN = "NNN12248621",
                            ListPrice = 40.0,
                            Price = 40.0,
                            Price100 = 35.0,
                            Price50 = 37.0,
                            Title = "NicoNico"
                        });
                });

            modelBuilder.Entity("LienXoChongUS.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Funny",
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Funny",
                            DisplayOrder = 2,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Romantic",
                            DisplayOrder = 3,
                            Name = "Romance"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
